---

- name: install pre-reqs for Docker to be installed
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_packages }}"

# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add specified repository into sources list
  shell: |
    sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
  args:
    executable: /bin/bash

- name: Update package lists
  shell: |
    apt-get update
  args:
    executable: /bin/bash

- name: install latest version of docker-ce
  package:
    name: docker-ce
    state: latest

- name: install Python wrapper for docker
  pip:
    name: docker
