---

- name: install Solr
  docker_image:
    name: solr:7.6.0

- name: Create Solr volume
  file:
    path: /opt/solr
    state: directory
    owner: 8983
    group: 8983

- name: Setup Solr within Systemd
  template:
    src: solr.service
    dest: /etc/systemd/system/solr.service

- name: Reload Systemd
  systemd:
    daemon_reload: yes

- name: Start Solr
  systemd:
    name: solr
    state: started
